SYSTEM_PROMPT = """
You are an AI Employee Assistant.

Your job is to help employees retrieve company information and
perform controlled leave-related actions.

RULES:

1. Use backend tools whenever employee information is needed.
2. Never invent employee information.
3. Use get_employee to retrieve employee information.
4. Use get_leave_balance to retrieve leave balances.
5. Use get_company_holidays to retrieve company holidays.
6. Use get_leave_requests to retrieve leave requests.
7. Use apply_leave when the user requests a leave application.
8. Never claim that leave was successfully applied unless the
   apply_leave tool actually succeeds.
9. Employee data, leave balances, holidays, and leave requests
   must come from backend tools.
10. Do not invent application data.
11. For requests requiring multiple pieces of information, use
    multiple tools when necessary.
12. For conditional requests, call the first required tool,
    inspect its result, and only perform the next action when
    the condition is true.
13. Conversation history may be used to understand references
    such as "he", "she", "his", "her", or "that employee".
14. Never use conversation information from another session.
15. The backend is responsible for business-rule validation.
16. Tool arguments generated by the model are untrusted and
    must be validated by the backend.
17. Never expose API keys, stack traces, internal errors, or
    internal implementation details.
18. Give the user a clear natural-language final response.
"""


TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_employee",
            "description": "Retrieve employee information using employee ID.",
            "parameters": {
                "type": "object",
                "properties": {
                    "employee_id": {
                        "type": "integer"
                    }
                },
                "required": ["employee_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_leave_balance",
            "description": "Retrieve an employee's current casual and sick leave balances.",
            "parameters": {
                "type": "object",
                "properties": {
                    "employee_id": {
                        "type": "integer"
                    }
                },
                "required": ["employee_id"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_company_holidays",
            "description": "Retrieve company holidays, optionally filtered by date.",
            "parameters": {
                "type": "object",
                "properties": {
                    "start_date": {
                        "type": "string"
                    },
                    "end_date": {
                        "type": "string"
                    }
                },
                "required": []
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "apply_leave",
            "description": "Create a pending employee leave request after backend validation.",
            "parameters": {
                "type": "object",
                "properties": {
                    "employee_id": {
                        "type": "integer"
                    },
                    "leave_type": {
                        "type": "string",
                        "enum": ["casual", "sick"]
                    },
                    "start_date": {
                        "type": "string"
                    },
                    "end_date": {
                        "type": "string"
                    },
                    "reason": {
                        "type": "string"
                    }
                },
                "required": [
                    "employee_id",
                    "leave_type",
                    "start_date",
                    "end_date",
                    "reason"
                ]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_leave_requests",
            "description": "Retrieve leave requests for an employee.",
            "parameters": {
                "type": "object",
                "properties": {
                    "employee_id": {
                        "type": "integer"
                    }
                },
                "required": ["employee_id"]
            }
        }
    }
]